# 数据源集合
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://117.72.110.81:3306/htuoj?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: HTUOJ
    password: sf2xxcJpmKYxF3is

rules:
  # 数据加密存储规则
  - !ENCRYPT
    # 需要加密的表集合
    tables:
      # 用户表
      user:
        # 用户表中哪些字段需要进行加密
        columns:
          mail:
            cipherColumn: mail
            encryptorName: common_encryptor
          password:
            cipherColumn: password
            encryptorName: common_encryptor
        # 是否按照密文字段查询
        queryWithCipherColumn: true
    # 加密算法
    encryptors:
      # 自定义加密算法名称
      common_encryptor:
        # 加密算法类型
        type: AES
        props:
          # AES 加密密钥
          aes-key-value: safsdfs45fds2f154
# 展现逻辑 SQL & 真实 SQL
props:
  sql-show: true